# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Init_Message.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys, time

import Main.Imagenes.sources
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Init_Mess(object):
    def __init__(self, username, worker):
        self.__username = username
        self.__worker = worker

    def setupUi(self, Init_Mess):
        Init_Mess.setObjectName("Init_Mess")
        Init_Mess.resize(389, 242)
        Init_Mess.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.background_image = QtWidgets.QLabel(Init_Mess)
        self.background_image.setGeometry(QtCore.QRect(0, 0, 391, 251))
        self.background_image.setText("")
        self.background_image.setPixmap(QtGui.QPixmap(":/iconos/fondo.png"))
        self.background_image.setScaledContents(True)
        self.background_image.setObjectName("background_image")
        self.image = QtWidgets.QLabel(Init_Mess)
        self.image.setGeometry(QtCore.QRect(20, 70, 111, 101))
        self.image.setStyleSheet("")
        self.image.setText("")
        self.image.setPixmap(QtGui.QPixmap(":/iconos/client.png"))
        self.image.setScaledContents(True)
        self.image.setObjectName("image")
        self.title = QtWidgets.QLabel(Init_Mess)
        self.title.setGeometry(QtCore.QRect(100, 20, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Shrikhand")
        font.setPointSize(24)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.title.setFont(font)
        self.title.setStyleSheet("color:rgb(255, 255, 255)")
        self.title.setObjectName("title")
        self.user = QtWidgets.QLabel(Init_Mess)
        self.user.setGeometry(QtCore.QRect(140, 80, 100, 16))
        font = QtGui.QFont()
        font.setFamily("Shrikhand")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.user.setFont(font)
        self.user.setStyleSheet("color:rgb(255, 255, 255)")
        self.user.setObjectName("user")
        self.change_user = QtWidgets.QLabel(Init_Mess)
        self.change_user.setGeometry(QtCore.QRect(249, 80, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Shrikhand")
        font.setPointSize(12)
        self.change_user.setFont(font)
        self.change_user.setStyleSheet("color:rgb(255, 255, 255)")
        self.change_user.setObjectName("change_user")
        self.change_worker = QtWidgets.QLabel(Init_Mess)
        self.change_worker.setGeometry(QtCore.QRect(140, 140, 200, 31))
        font = QtGui.QFont()
        font.setFamily("Shrikhand")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.change_worker.setFont(font)
        self.change_worker.setStyleSheet("color:rgb(255, 255, 255)")
        self.change_worker.setObjectName("change_worker")
        self.pushButton = QtWidgets.QPushButton(Init_Mess)
        self.pushButton.setGeometry(QtCore.QRect(100, 200, 191, 31))
        self.pushButton.setDefault(True)
        self.pushButton.setStyleSheet("border-radius:5px;\n"
        
"border:2px solid white;\n"
"color:rgb(255, 255, 255);\n"
"font: 14pt \"Shrikhand\";\n"
"\n"
"hover{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color:rgb(255, 255, 255)\n"
"\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.close_Window)

        self.retranslateUi(Init_Mess)
        QtCore.QMetaObject.connectSlotsByName(Init_Mess)

    def retranslateUi(self, Init_Mess):
        _translate = QtCore.QCoreApplication.translate
        Init_Mess.setWindowTitle(_translate("Init_Mess", "TERAN EIRL"))
        self.title.setText(_translate("Init_Mess", "Bienvenido"))
        self.user.setText(_translate("Init_Mess", "Usuario:"))
        self.change_user.setText(_translate("Init_Mess", self.__username))
        self.change_worker.setText(_translate("Init_Mess", self.__worker))
        self.pushButton.setText(_translate("Init_Mess", "Ok"))


    def close_Window(self):
        sys.exit()





    def run_Mess(self, u_name, wrk):
        app = QtWidgets.QApplication(sys.argv)
        run = QtWidgets.QDialog()
        #==============================================
        window = Ui_Init_Mess(u_name, wrk)
        window.setupUi(run)
        run.show()

        sys.exit(app.exec_())

