# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fersystem.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import *
from PyQt5.QtWidgets import QMessageBox

from Main.TOOLS.Tools import Crud_DB, MessageBX


class InformationDi(object):
    def __init__(self, username, worker):
        self.__username = username
        self.__worker = worker

    def setupUi(self, Init_Mess):
        Init_Mess.setObjectName("Init_Mess")
        Init_Mess.resize(389, 242)
        Init_Mess.setStyleSheet("QPushButton:hover{\n"
                                "    background-color: rgb(0, 0, 0);\n"
                                "}")
        self.background_image = QtWidgets.QLabel(Init_Mess)
        self.background_image.setGeometry(QtCore.QRect(0, 0, 391, 251))
        self.background_image.setText("")
        self.background_image.setPixmap(QtGui.QPixmap(":/iconos/fondo.png"))
        self.background_image.setScaledContents(True)
        self.background_image.setObjectName("background_image")
        self.image = QtWidgets.QLabel(Init_Mess)
        self.image.setGeometry(QtCore.QRect(20, 70, 111, 101))
        self.image.setStyleSheet("")
        self.image.setText("")
        self.image.setPixmap(QtGui.QPixmap(":/iconos/client.png"))
        self.image.setScaledContents(True)
        self.image.setObjectName("image")
        self.title = QtWidgets.QLabel(Init_Mess)
        self.title.setGeometry(QtCore.QRect(100, 20, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Shrikhand")
        font.setPointSize(24)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.title.setFont(font)
        self.title.setStyleSheet("color:rgb(255, 255, 255)")
        self.title.setObjectName("title")
        self.user = QtWidgets.QLabel(Init_Mess)
        self.user.setGeometry(QtCore.QRect(140, 80, 100, 16))
        font = QtGui.QFont()
        font.setFamily("Shrikhand")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.user.setFont(font)
        self.user.setStyleSheet("color:rgb(255, 255, 255)")
        self.user.setObjectName("user")
        self.change_user = QtWidgets.QLabel(Init_Mess)
        self.change_user.setGeometry(QtCore.QRect(249, 80, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Shrikhand")
        font.setPointSize(12)
        self.change_user.setFont(font)
        self.change_user.setStyleSheet("color:rgb(255, 255, 255)")
        self.change_user.setObjectName("change_user")
        self.change_worker = QtWidgets.QLabel(Init_Mess)
        self.change_worker.setGeometry(QtCore.QRect(140, 140, 200, 31))
        font = QtGui.QFont()
        font.setFamily("Shrikhand")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.change_worker.setFont(font)
        self.change_worker.setStyleSheet("color:rgb(255, 255, 255)")
        self.change_worker.setObjectName("change_worker")
        self.pushButton = QtWidgets.QPushButton(Init_Mess)
        self.pushButton.setGeometry(QtCore.QRect(100, 200, 191, 31))
        self.pushButton.setDefault(True)
        self.pushButton.setStyleSheet("border-radius:5px;\n"

                                      "border:2px solid white;\n"
                                      "color:rgb(255, 255, 255);\n"
                                      "font: 14pt \"Shrikhand\";\n"
                                      "\n"
                                      "hover{\n"
                                      "    background-color: rgb(0, 0, 0);\n"
                                      "    color:rgb(255, 255, 255)\n"
                                      "\n"
                                      "}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.close_Window)

        self.retranslateUi(Init_Mess)
        QtCore.QMetaObject.connectSlotsByName(Init_Mess)

    def retranslateUi(self, Init_Mess):
        _translate = QtCore.QCoreApplication.translate
        Init_Mess.setWindowTitle(_translate("Init_Mess", "TERAN EIRL"))
        self.title.setText(_translate("Init_Mess", "Bienvenido"))
        self.user.setText(_translate("Init_Mess", "Usuario:"))
        self.change_user.setText(_translate("Init_Mess", self.__username))
        self.change_worker.setText(_translate("Init_Mess", self.__worker))
        self.pushButton.setText(_translate("Init_Mess", "Ok"))

    def close_Window(self):
        sys.exit()

def run_Mess(u_name, wrk):
    app = QtWidgets.QApplication(sys.argv)
    run = QtWidgets.QDialog()
    # ==============================================
    window = InformationDi(u_name, wrk)
    window.setupUi(run)
    run.show()

    sys.exit(app.exec_())
class Login_Menu(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(735, 430)
        MainWindow.setWhatsThis("")
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("QMainWindow{\n"
                                 "    background-color: rgb(0, 0, 0);\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:hover{\n"
                                 "background:black;\n"
                                 "color:red;\n"
                                 "border-radius:15px;\n"
                                 "font-weight: bold;\n"
                                 "}\n"
                                 "")
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setWindowIcon(QIcon("../Imagenes/Principal.ico"))

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setGeometry(QtCore.QRect(150, 0, 381, 120))
        font = QtGui.QFont()
        font.setFamily("Shrikhand")
        font.setPointSize(26)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.titleLabel.setFont(font)
        self.titleLabel.setStyleSheet("color:white;")
        self.titleLabel.setTextFormat(QtCore.Qt.PlainText)
        self.titleLabel.setObjectName("titleLabel")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(330, 90, 301, 81))
        font = QtGui.QFont()
        font.setFamily("Shrikhand")
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("color:rgb(255, 255, 255)")
        self.groupBox.setFlat(True)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.typeWorker = QtWidgets.QComboBox(self.groupBox)
        self.typeWorker.setGeometry(QtCore.QRect(60, 30, 231, 22))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.typeWorker.setFont(font)
        self.typeWorker.setAutoFillBackground(False)

        self.typeWorker.setStyleSheet("color: rgb(0,0,0)")

        self.typeWorker.setObjectName("typeWorker")
        self.workerImage = QtWidgets.QLabel(self.groupBox)
        self.workerImage.setGeometry(QtCore.QRect(10, 20, 41, 31))
        self.workerImage.setStyleSheet("border-radius:15px;\n"
                                       "background:white;")
        self.workerImage.setText("")
        #self.workerImage.setPixmap(QtGui.QPixmap("../Imagenes/worker.png"))
        self.workerImage.setScaledContents(True)
        self.workerImage.setObjectName("workerImage")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(330, 190, 301, 151))
        font = QtGui.QFont()
        font.setFamily("Shrikhand")
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("color:white;")
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.entryUser = QtWidgets.QLineEdit(self.groupBox_2)
        self.entryUser.setGeometry(QtCore.QRect(70, 30, 221, 31))
        self.entryUser.setStyleSheet("background:transparent;\n"
                                     "border:none;\n"
                                     "border-bottom:1px solid white;")
        self.entryUser.setObjectName("entryUser")
        self.entryPassword = QtWidgets.QLineEdit(self.groupBox_2)
        self.entryPassword.setGeometry(QtCore.QRect(70, 90, 221, 31))
        self.entryPassword.setStyleSheet("background:transparent;\n"
                                         "border:none;\n"
                                         "border-bottom:1px solid white;")
        self.entryPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.entryPassword.setObjectName("entryPassword")
        self.userImage = QtWidgets.QLabel(self.groupBox_2)
        self.userImage.setGeometry(QtCore.QRect(20, 30, 41, 31))
        self.userImage.setStyleSheet("border-radius:15px;\n"
                                     "background:white;")
        self.userImage.setText("")
        #self.userImage.setPixmap(QtGui.QPixmap("../Imagenes/workerUser.png"))
        self.userImage.setScaledContents(True)
        self.userImage.setObjectName("userImage")
        self.passwordImage = QtWidgets.QLabel(self.groupBox_2)
        self.passwordImage.setGeometry(QtCore.QRect(20, 90, 41, 31))
        self.passwordImage.setStyleSheet("border-radius:15px;\n"
                                         "background:white;")
        self.passwordImage.setText("")
       # self.passwordImage.setPixmap(QtGui.QPixmap("../Imagenes/workerPassword.png"))
        self.passwordImage.setScaledContents(True)
        self.passwordImage.setObjectName("passwordImage")
        self.ingresarBTN = QtWidgets.QPushButton(self.centralwidget)
        self.ingresarBTN.setGeometry(QtCore.QRect(410, 340, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Shrikhand")
        font.setPointSize(16)
        self.ingresarBTN.setFont(font)
        self.ingresarBTN.setStyleSheet("color:white;\n"
                                       "border-style: outset;\n"
                                       "border-radius:15px;\n"
                                       "border-width:1px;\n"
                                       "border-color:white;\n"
                                       "\n"
                                       "\n"
                                       "\n"
                                       "")
        self.ingresarBTN.setObjectName("ingresarBTN")

        #============================Conectar el boton ingresar con la funcion log ==============
        self.ingresarBTN.clicked.connect(self.log)
        #====================================================================================

        self.LineaSeparadora = QtWidgets.QFrame(self.centralwidget)
        self.LineaSeparadora.setGeometry(QtCore.QRect(290, 90, 20, 301))
        self.LineaSeparadora.setStyleSheet("color:rgb(255, 112, 55)")
        self.LineaSeparadora.setFrameShape(QtWidgets.QFrame.VLine)
        self.LineaSeparadora.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.LineaSeparadora.setObjectName("LineaSeparadora")
        self.ToolImag = QtWidgets.QLabel(self.centralwidget)
        self.ToolImag.setGeometry(QtCore.QRect(30, 110, 241, 241))
        self.ToolImag.setStyleSheet("")
        self.ToolImag.setText("")
        #self.ToolImag.setPixmap(QtGui.QPixmap("../Imagenes/logo2_preview_rev_1.png"))
        self.ToolImag.setScaledContents(True)
        self.ToolImag.setObjectName("ToolImag")
        self.fondoImagen = QtWidgets.QLabel(self.centralwidget)
        self.fondoImagen.setGeometry(QtCore.QRect(-170, -70, 1280, 481))
        self.fondoImagen.setText("")
        #self.fondoImagen.setPixmap(QtGui.QPixmap("../Imagenes/fondo.png"))
        self.fondoImagen.setScaledContents(True)
        self.fondoImagen.setObjectName("fondoImagen")
        self.fondoImagen.raise_()
        self.titleLabel.raise_()
        self.groupBox.raise_()
        self.groupBox_2.raise_()
        self.ingresarBTN.raise_()
        self.LineaSeparadora.raise_()
        self.ToolImag.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Teran EIRL"))
        self.titleLabel.setText(_translate("MainWindow", "TeranSystem Login"))
        self.groupBox.setTitle(_translate("MainWindow", "Trabajador"))

        #=========================Items para el Combobox ========================
        self.type_workers = {"ADMINISTRADOR":"A", "VENDEDOR":"V", "CAJERO":"C" }
        #========================================================================
        self.typeWorker.addItems(self.type_workers)
        self.groupBox_2.setTitle(_translate("MainWindow", "Credenciales"))
        self.entryUser.setPlaceholderText(_translate("MainWindow", "Usuario"))
        self.entryPassword.setPlaceholderText(_translate("MainWindow", "Contraseña"))
        self.ingresarBTN.setText(_translate("MainWindow", "Ingresar"))

    def log(self):
        bd = Crud_DB()
        msbox = MessageBX()

        if self.entryUser.text() == "" or  self.entryPassword.text() == "":
            msbox.setTxt("Ingreso a FerSystem Teran", "Falta datos!")
            msbox.insertIcon("Imagenes/cancel.ico", QMessageBox.Warning)
            msbox.exec_()
        else:
            try:


                acceso = bd.login(self.entryUser.text(), self.entryPassword.text(),self.type_workers[self.typeWorker.currentText()])

                if acceso:
                    msbox.setTxt("Bienvenido","Credenciales Correctas")
                    msbox.insertIcon("Imagenes/accept.ico", QMessageBox.Information)
                    msbox.exec_()
                    sys.exit()

                else:
                    msbox.setTxt("Bienvenido", "Credenciales Incorrectas")
                    msbox.insertIcon("Imagenes/cancel.ico", QMessageBox.Warning)
                    msbox.exec_()

            except Exception as e:
                msbox.setTxt("Bienvenido", f"Error Critico\nInformar al desarrollador\nError:{e.__str__()}")
                msbox.insertIcon("Imagenes/cancel.ico", QMessageBox.Warning)
                msbox.exec_()