# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Informacion.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog

import  Main.Imagenes.sources

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(372, 444)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/iconos/Principal.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 371, 451))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/iconos/logo_login.PNG"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 331, 391))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(116, 10, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Sistema de ventas FERRETERIA TERA"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">Sistema de Ventas diseñado para la </span></p><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">&quot;Ferreteria Teran&quot;.</span></p><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">El cual contara con lo suficiente para </span></p><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">administrar el negocio.</span></p><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\"><br/></span></p><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">Este Proyecto fue realizado por el Grupo Nº3 </span></p><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">conformado por:</span></p><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">-Brayan Alvitez Fernandez </span></p><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">-Luis Quintana Muñoz </span></p><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">-Cristian Bardales Isai</span></p><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">-Piero Angel Salazar </span></p><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#000000;\"><br/></span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "Informacion"))


class ShowInformation(QDialog):
    def __init__(self):
        super().__init__()

    def showMe(self):
        self.info = Ui_Dialog()
        self.info.setupUi(self)

        self.show()