# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Proveedor_registro.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

#Import el archivo PY que contiene las imagenes
import Main.Imagenes.sources

class Ui_DetallesProveedor(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(411, 345)
        Dialog.setStyleSheet("QPushButton{border-radius:15px;\n"
"border:2px solid black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(2, 198, 201);\n"
"}\n"
"QPushButton:pressed { \n"
"    \n"
"    background-color: rgb(32, 90, 143);\n"
"    border-style: inset;\n"
"}\n"
"QLineEdit{\n"
"background:transparent;\n"
"border:none;\n"
"border-bottom:1px solid white;\n"
"    font: 57 12pt \"Roboto\";\n"
"}")
        self.fondo = QtWidgets.QLabel(Dialog)
        self.fondo.setGeometry(QtCore.QRect(0, 0, 461, 351))
        self.fondo.setText("")
        self.fondo.setPixmap(QtGui.QPixmap(":/iconos/fondo2.PNG"))
        self.fondo.setScaledContents(True)
        self.fondo.setObjectName("fondo")
        self.tituto = QtWidgets.QLabel(Dialog)
        self.tituto.setGeometry(QtCore.QRect(110, 10, 251, 31))
        self.tituto.setStyleSheet("font: 57 16pt \"Roboto\";\n"
"color:rgb(255, 255, 255)")
        self.tituto.setObjectName("tituto")
        self.gb_Contacto = QtWidgets.QGroupBox(Dialog)
        self.gb_Contacto.setGeometry(QtCore.QRect(20, 160, 371, 121))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.gb_Contacto.setFont(font)
        self.gb_Contacto.setObjectName("gb_Contacto")
        self.ln_nombreContacto = QtWidgets.QLineEdit(self.gb_Contacto)
        self.ln_nombreContacto.setGeometry(QtCore.QRect(190, 20, 171, 20))
        self.ln_nombreContacto.setObjectName("ln_nombreContacto")
        self.lbl_contac = QtWidgets.QLabel(self.gb_Contacto)
        self.lbl_contac.setGeometry(QtCore.QRect(20, 20, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lbl_contac.setFont(font)
        self.lbl_contac.setObjectName("lbl_contac")
        self.ln_cargoContacto = QtWidgets.QLineEdit(self.gb_Contacto)
        self.ln_cargoContacto.setGeometry(QtCore.QRect(190, 50, 171, 20))
        self.ln_cargoContacto.setObjectName("ln_cargoContacto")
        self.lbl_cargocont = QtWidgets.QLabel(self.gb_Contacto)
        self.lbl_cargocont.setGeometry(QtCore.QRect(20, 50, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lbl_cargocont.setFont(font)
        self.lbl_cargocont.setObjectName("lbl_cargocont")
        self.lbl_correo = QtWidgets.QLabel(self.gb_Contacto)
        self.lbl_correo.setGeometry(QtCore.QRect(20, 80, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lbl_correo.setFont(font)
        self.lbl_correo.setObjectName("lbl_correo")
        self.ln_correo = QtWidgets.QLineEdit(self.gb_Contacto)
        self.ln_correo.setGeometry(QtCore.QRect(190, 80, 171, 20))
        self.ln_correo.setObjectName("ln_correo")
        self.gb_Direccion = QtWidgets.QGroupBox(Dialog)
        self.gb_Direccion.setGeometry(QtCore.QRect(20, 40, 371, 101))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.gb_Direccion.setFont(font)
        self.gb_Direccion.setObjectName("gb_Direccion")
        self.ln_pais = QtWidgets.QLineEdit(self.gb_Direccion)
        self.ln_pais.setGeometry(QtCore.QRect(100, 50, 171, 20))
        self.ln_pais.setObjectName("ln_pais")
        self.lbl_pais = QtWidgets.QLabel(self.gb_Direccion)
        self.lbl_pais.setGeometry(QtCore.QRect(30, 50, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lbl_pais.setFont(font)
        self.lbl_pais.setObjectName("lbl_pais")
        self.lbl_ciudad = QtWidgets.QLabel(self.gb_Direccion)
        self.lbl_ciudad.setGeometry(QtCore.QRect(30, 20, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lbl_ciudad.setFont(font)
        self.lbl_ciudad.setObjectName("lbl_ciudad")
        self.ln_ciudad = QtWidgets.QLineEdit(self.gb_Direccion)
        self.ln_ciudad.setGeometry(QtCore.QRect(100, 20, 171, 20))
        self.ln_ciudad.setObjectName("ln_ciudad")
        self.btn_confirmar = QtWidgets.QPushButton(Dialog)
        self.btn_confirmar.setGeometry(QtCore.QRect(140, 290, 131, 41))
        self.btn_confirmar.setStyleSheet("color:rgb(255, 255, 255)")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/iconos/done.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_confirmar.setIcon(icon)
        self.btn_confirmar.setIconSize(QtCore.QSize(30, 30))
        self.btn_confirmar.setObjectName("btn_confirmar")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.tituto.setText(_translate("Dialog", "Mas Opcion de Direccion"))
        self.gb_Contacto.setTitle(_translate("Dialog", "Contacto"))
        self.lbl_contac.setText(_translate("Dialog", "Nombre del Contacto:"))
        self.lbl_cargocont.setText(_translate("Dialog", "Cargo de Contacto:"))
        self.lbl_correo.setText(_translate("Dialog", "Correo:"))
        self.gb_Direccion.setTitle(_translate("Dialog", "Direccion"))
        self.lbl_pais.setText(_translate("Dialog", "Pais:"))
        self.lbl_ciudad.setText(_translate("Dialog", "Ciudad:"))
        self.btn_confirmar.setText(_translate("Dialog", "Confirmar"))

