# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'carga.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
import sys
import time


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QThread, pyqtSignal, Qt
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QMainWindow, QApplication, QWidget



class LoadSystem(object):
    def setupUi(self, LoadSystem):
        LoadSystem.setObjectName("LoadSystem")
        LoadSystem.resize(370, 221)
        LoadSystem.setWindowFlag(Qt.FramelessWindowHint)
        LoadSystem.setAttribute(Qt.WA_TranslucentBackground)

        self.label = QtWidgets.QLabel(LoadSystem)
        self.label.setGeometry(QtCore.QRect(0, 0, 401, 351))
        self.label.setText("")
        #elf.label.setPixmap(QtGui.QPixmap("../Imagenes/fondo.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(LoadSystem)
        self.label_2.setGeometry(QtCore.QRect(80, 10, 211, 61))
        self.label_2.setStyleSheet("color:rgb(255, 255, 255);\n"
                                   "font: bold 28pt \"Calibri\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(LoadSystem)
        self.label_3.setGeometry(QtCore.QRect(100, 70, 171, 111))
        self.label_3.setText("")
        #self.label_3.setPixmap(QtGui.QPixmap("../Imagenes/logo2_preview_rev_1.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.cargador = QtWidgets.QProgressBar(LoadSystem)
        self.cargador.setGeometry(QtCore.QRect(40, 200, 301, 16))
        self.cargador.setStyleSheet("color: rgb(0, 0, 0);\n"
                                    "font: bold 9pt \"Calibri\";\n"
                                    "border-radius:5px;\n"
                                    "border: 1px solid gray;\n"
                                    "")
        self.cargador.setProperty("value", 0)
        self.cargador.setTextVisible(True)
        self.cargador.setInvertedAppearance(False)
        self.cargador.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.cargador.setObjectName("cargador")
        self.cargador.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4 = QtWidgets.QLabel(LoadSystem)
        self.label_4.setGeometry(QtCore.QRect(40, 180, 181, 16))
        self.label_4.setStyleSheet("color:rgb(255, 255, 255);\n"
                                   "font: bold 10pt \"Calibri\";")
        self.label_4.setObjectName("label_4")

        self.retranslateUi(LoadSystem)
        QtCore.QMetaObject.connectSlotsByName(LoadSystem)

    def retranslateUi(self, LoadSystem):
        _translate = QtCore.QCoreApplication.translate
        LoadSystem.setWindowTitle(_translate("LoadSystem", "TeranSystem"))
        self.label_2.setText(_translate("LoadSystem", "Teran System"))
        self.label_4.setText(_translate("LoadSystem", "Iniciando..."))


